name: Gradle Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Cache gradle
        uses: actions/cache@v2.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up cocoapods-generate
        if: matrix.os == 'macOS-latest'
        run: gem install cocoapods-generate

      - name: Set up local secrets
        env:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
        run: |
          echo mapbox.download.key=$MAPBOX_DOWNLOADS_TOKEN > local.properties
          echo mmapp.config.netrc=true >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run checks
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew check

      - name: Run iOS tests
        if: matrix.os == 'macOS-latest'
        run: ./gradlew iosTest
