name: Publish Docs

on:
  push:
    # TODO: Eventually this will only run on tagged releases
    branches: [ main ]
    tags:
      - "*"

jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up cocoapods-generate
        if: matrix.os == 'macOS-latest'
        run: gem install cocoapods-generate

      - name: Set up local secrets
        env:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
        run: |
          echo mapbox.download.key=$MAPBOX_DOWNLOADS_TOKEN > local.properties
          echo mmapp.config.netrc=true >> local.properties

      - name: Build Dokka docs
        run: ./gradlew :mmapp:dokkaHtml --no-daemon --no-parallel

      - name: Deploy 🚀
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: mmapp/build/dokka/html
          SINGLE_COMMIT: true
