name: Publish Docs

on:
  push:
    # TODO: Eventually this will only run on tagged releases
    branches: [ master ]
    tags:
      - "*"

jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Dokka docs
        run: ./gradlew :library:dokkaHtml --no-daemon --no-parallel

      - name: Deploy 🚀
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/dokka/html
          SINGLE_COMMIT: true
