name: Publish Snapshot

on:
  push:
    branches: [ main ]
    tags:
      - "*"

jobs:
  build-library:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up cocoapods-generate
        if: matrix.os == 'macOS-latest'
        run: gem install cocoapods-generate

      - name: Set up local secrets
        env:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
        run: |
          echo mapbox.download.key=$MAPBOX_DOWNLOADS_TOKEN > local.properties
          echo mmapp.config.netrc=true >> local.properties

      - name: Publish artifacts
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        run: ./gradlew :library:uploadArchives --no-daemon --no-parallel
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up cocoapods-generate
        if: matrix.os == 'macOS-latest'
        run: gem install cocoapods-generate

      - name: Set up local secrets
        env:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
        run: |
          echo mapbox.download.key=$MAPBOX_DOWNLOADS_TOKEN > local.properties
          echo mmapp.config.netrc=true >> local.properties

      - name: Publish artifacts
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        run: ./gradlew :gradle-plugin:uploadArchives --no-daemon --no-parallel
